import { Iuser } from "../model/user.interface"



export const bikes : Array<Iuser> = [
    { slot: "A1", isActive: false, vehicleType: 'bike', userId: 1, vehicleNumber: [] },
    { slot: "A2", isActive: false, vehicleType: 'bike', userId: 2, vehicleNumber: [] },
    { slot: "A3", isActive: false, vehicleType: 'bike', userId: 3, vehicleNumber: [] },
    { slot: "A4", isActive: false, vehicleType: 'bike', userId: 4, vehicleNumber: [] },
    { slot: "A5", isActive: false, vehicleType: 'bike', userId: 5, vehicleNumber: [] },
    { slot: "A6", isActive: false, vehicleType: 'bike', userId: 6, vehicleNumber: [] },
    { slot: "A7", isActive: false, vehicleType: 'bike', userId: 7, vehicleNumber: [] },
    { slot: "A8", isActive: false, vehicleType: 'bike', userId: 8, vehicleNumber: [] },
    { slot: "A9", isActive: false, vehicleType: 'bike', userId: 9, vehicleNumber: [] },
    { slot: "A10", isActive: false, vehicleType: 'bike', userId: 10, vehicleNumber: [] },
    { slot: "A11", isActive: false, vehicleType: 'bike', userId: 11, vehicleNumber: [] },
    { slot: "A12", isActive: false, vehicleType: 'bike', userId: 12, vehicleNumber: [] },
    { slot: "B1", isActive: false, vehicleType: 'bike', userId: 13, vehicleNumber: [] },
    { slot: "B2", isActive: false, vehicleType: 'bike', userId: 14, vehicleNumber: [] },
    { slot: "B3", isActive: false, vehicleType: 'bike', userId: 15, vehicleNumber: [] },
    { slot: "B4", isActive: false, vehicleType: 'bike', userId: 16, vehicleNumber: [] },
    { slot: "B5", isActive: false, vehicleType: 'bike', userId: 17, vehicleNumber: [] },
    { slot: "B6", isActive: false, vehicleType: 'bike', userId: 18, vehicleNumber: [] },
    { slot: "B7", isActive: false, vehicleType: 'bike', userId: 19, vehicleNumber: [] },
    { slot: "B8", isActive: false, vehicleType: 'bike', userId: 20, vehicleNumber: [] },
    { slot: "B9", isActive: false, vehicleType: 'bike', userId: 21, vehicleNumber: [] },
    { slot: "B10", isActive: false, vehicleType: 'bike', userId: 22, vehicleNumber: [] },
    { slot: "B11", isActive: false, vehicleType: 'bike', userId: 23, vehicleNumber: [] },
    { slot: "B12", isActive: false, vehicleType: 'bike', userId: 24, vehicleNumber: [] },
    { slot: "C1", isActive: false, vehicleType: 'bike', userId: 25, vehicleNumber: [] },
    { slot: "C2", isActive: false, vehicleType: 'bike', userId: 26, vehicleNumber: [] },
    { slot: "C3", isActive: false, vehicleType: 'bike', userId: 27, vehicleNumber: [] },
    { slot: "C4", isActive: false, vehicleType: 'bike', userId: 28, vehicleNumber: [] },
    { slot: "C5", isActive: false, vehicleType: 'bike', userId: 29, vehicleNumber: [] },
    { slot: "C6", isActive: false, vehicleType: 'bike', userId: 30, vehicleNumber: [] },
    { slot: "C7", isActive: false, vehicleType: 'bike', userId: 31, vehicleNumber: [] },
    { slot: "C8", isActive: false, vehicleType: 'bike', userId: 32, vehicleNumber: [] },
    { slot: "C9", isActive: false, vehicleType: 'bike', userId: 33, vehicleNumber: [] },
    { slot: "C10", isActive: false, vehicleType: 'bike', userId: 34, vehicleNumber: [] },
    { slot: "C11", isActive: false, vehicleType: 'bike', userId: 35, vehicleNumber: [] },
    { slot: "C12", isActive: false, vehicleType: 'bike', userId: 36, vehicleNumber: [] },
    { slot: "D1", isActive: false, vehicleType: 'bike', userId: 37, vehicleNumber: [] },
    { slot: "D2", isActive: false, vehicleType: 'bike', userId: 38, vehicleNumber: [] },
    { slot: "D3", isActive: false, vehicleType: 'bike', userId: 39, vehicleNumber: [] },
    { slot: "D4", isActive: false, vehicleType: 'bike', userId: 40, vehicleNumber: [] },
    { slot: "D5", isActive: false, vehicleType: 'bike', userId: 41, vehicleNumber: [] },
    { slot: "D6", isActive: false, vehicleType: 'bike', userId: 42, vehicleNumber: [] },
    { slot: "D7", isActive: false, vehicleType: 'bike', userId: 43, vehicleNumber: [] },
    { slot: "D8", isActive: false, vehicleType: 'bike', userId: 44, vehicleNumber: [] },
    { slot: "D9", isActive: false, vehicleType: 'bike', userId: 45, vehicleNumber: [] },
    { slot: "D10", isActive: false, vehicleType: 'bike', userId: 46, vehicleNumber: [] },
    { slot: "D11", isActive: false, vehicleType: 'bike', userId: 47, vehicleNumber: [] },
    { slot: "D12", isActive: false, vehicleType: 'bike', userId: 48, vehicleNumber: [] },
]


export const cars : Array<Iuser> = [
    { slot: "A1", isActive: false, vehicleType: 'car', userId: 1, vehicleNumber: [] },
    { slot: "A2", isActive: false, vehicleType: 'car', userId: 2, vehicleNumber: [] },
    { slot: "A3", isActive: false, vehicleType: 'car', userId: 3, vehicleNumber: [] },
    { slot: "A4", isActive: false, vehicleType: 'car', userId: 4, vehicleNumber: [] },
    { slot: "A5", isActive: false, vehicleType: 'car', userId: 5, vehicleNumber: [] },
    { slot: "A6", isActive: false, vehicleType: 'car', userId: 6, vehicleNumber: [] },
    { slot: "A7", isActive: false, vehicleType: 'car', userId: 7, vehicleNumber: [] },
    { slot: "A8", isActive: false, vehicleType: 'car', userId: 8, vehicleNumber: [] },
    { slot: "A9", isActive: false, vehicleType: 'car', userId: 9, vehicleNumber: [] },
    { slot: "A10", isActive: false, vehicleType: 'car', userId: 10, vehicleNumber: [] },
    { slot: "A11", isActive: false, vehicleType: 'car', userId: 11, vehicleNumber: [] },
    { slot: "A12", isActive: false, vehicleType: 'car', userId: 12, vehicleNumber: [] },
    { slot: "B1", isActive: false, vehicleType: 'car', userId: 13, vehicleNumber: [] },
    { slot: "B2", isActive: false, vehicleType: 'car', userId: 14, vehicleNumber: [] },
    { slot: "B3", isActive: false, vehicleType: 'car', userId: 15, vehicleNumber: [] },
    { slot: "B4", isActive: false, vehicleType: 'car', userId: 16, vehicleNumber: [] },
    { slot: "B5", isActive: false, vehicleType: 'car', userId: 17, vehicleNumber: [] },
    { slot: "B6", isActive: false, vehicleType: 'car', userId: 18, vehicleNumber: [] },
    { slot: "B7", isActive: false, vehicleType: 'car', userId: 19, vehicleNumber: [] },
    { slot: "B8", isActive: false, vehicleType: 'car', userId: 20, vehicleNumber: [] },
    { slot: "B9", isActive: false, vehicleType: 'car', userId: 21, vehicleNumber: [] },
    { slot: "B10", isActive: false, vehicleType: 'car', userId: 22, vehicleNumber: [] },
    { slot: "B11", isActive: false, vehicleType: 'car', userId: 23, vehicleNumber: [] },
    { slot: "B12", isActive: false, vehicleType: 'car', userId: 24, vehicleNumber: [] },
    { slot: "C1", isActive: false, vehicleType: 'car', userId: 25, vehicleNumber: [] },
    { slot: "C2", isActive: false, vehicleType: 'car', userId: 26, vehicleNumber: [] },
    { slot: "C3", isActive: false, vehicleType: 'car', userId: 27, vehicleNumber: [] },
    { slot: "C4", isActive: false, vehicleType: 'car', userId: 28, vehicleNumber: [] },
    { slot: "C5", isActive: false, vehicleType: 'car', userId: 29, vehicleNumber: [] },
    { slot: "C6", isActive: false, vehicleType: 'car', userId: 30, vehicleNumber: [] },
    { slot: "C7", isActive: false, vehicleType: 'car', userId: 31, vehicleNumber: [] },
    { slot: "C8", isActive: false, vehicleType: 'car', userId: 32, vehicleNumber: [] },
    { slot: "C9", isActive: false, vehicleType: 'car', userId: 33, vehicleNumber: [] },
    { slot: "C10", isActive: false, vehicleType: 'car', userId: 34, vehicleNumber: [] },
    { slot: "C11", isActive: false, vehicleType: 'car', userId: 35, vehicleNumber: [] },
    { slot: "C12", isActive: false, vehicleType: 'car', userId: 36, vehicleNumber: [] },
    { slot: "D1", isActive: false, vehicleType: 'car', userId: 37, vehicleNumber: [] },
    { slot: "D2", isActive: false, vehicleType: 'car', userId: 38, vehicleNumber: [] },
    { slot: "D3", isActive: false, vehicleType: 'car', userId: 39, vehicleNumber: [] },
    { slot: "D4", isActive: false, vehicleType: 'car', userId: 40, vehicleNumber: [] },
    { slot: "D5", isActive: false, vehicleType: 'car', userId: 41, vehicleNumber: [] },
    { slot: "D6", isActive: false, vehicleType: 'car', userId: 42, vehicleNumber: [] },
    { slot: "D7", isActive: false, vehicleType: 'car', userId: 43, vehicleNumber: [] },
    { slot: "D8", isActive: false, vehicleType: 'car', userId: 44, vehicleNumber: [] },
    { slot: "D9", isActive: false, vehicleType: 'car', userId: 45, vehicleNumber: [] },
    { slot: "D10", isActive: false, vehicleType: 'car', userId: 46, vehicleNumber: [] },
    { slot: "D11", isActive: false, vehicleType: 'car', userId: 47, vehicleNumber: [] },
    { slot: "D12", isActive: false, vehicleType: 'car', userId: 48, vehicleNumber: [] },
]