// import { Iuser } from "../model/user.interface";


// export const bikes: Array<Iuser> = [
//     { slot: "A1", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "A2", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "A3", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "A4", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "A5", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "A6", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "A7", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "A8", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "A9", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "A10", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "A11", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "A12", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B1", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B2", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B3", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B4", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B5", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B6", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B7", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B8", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B9", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B10", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B11", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "B12", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C1", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C2", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C3", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C4", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C5", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C6", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C7", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C8", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C9", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C10", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C11", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "C12", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D1", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D2", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D3", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D4", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D5", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D6", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D7", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D8", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D9", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D10", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D11", isActive: false, userId: null, vehicleNumber: '' },
//     { slot: "D12", isActive: false, userId: null, vehicleNumber: '' },
// ];


// export const cars: Array<Iuser> = [
    
// ];
